spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pr1_lesson2
    driverClassName: org.postgresql.Driver
    username: postgres
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

flyway:
  locations:
    classpath: db/migration