spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/pr1_lesson1
    url: jdbc:postgresql://localhost:5430/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
#    password: admin
    password: pass

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

#    open-in-view: true
flyway:
  locations:
    classpath: db/migration